import type { Theme } from './types.js';

/** The hedged, citation-laden prose of the seminar room. */
export const academia: Theme = {
  id: 'academia',
  name: 'Academia',
  description: 'It could be argued that this placeholder problematizes the discourse.',
  emoji: '🎓',
  accent: '#6e2b2b',
  defaultIntensity: 0.4,
  origin:
    'The hedged, citation-laden prose of the seminar room — where nothing simply ' +
    'is, it is "situated," "troubled," and "always already" something else ' +
    '(see Figure 3).',
  glossary: {
    discourse: 'the ongoing scholarly conversation about a topic',
    hegemony: 'dominance so settled it passes for normal',
    dialectic: 'progress through clashing opposed ideas',
    epistemology: 'the study of how we know what we know',
    ontology: 'the study of what exists',
    problematize: 'treat as a problem worth questioning',
    interrogate: 'examine critically',
    liminal: 'on a threshold; in an in-between state',
    hermeneutic: 'concerning interpretation',
    praxis: 'theory put into practice',
    heuristic: 'a rough, useful rule of thumb',
    paradigm: 'a dominant framework of thought',
    methodology: 'the study and rationale of methods',
    qualitative: 'about qualities and meaning, not numbers',
    empirical: 'based on observation and evidence',
    theoretical: 'about theory rather than practice',
    intersectional: 'where multiple identities overlap',
    postcolonial: 'after, and critical of, empire',
    deconstruct: 'take apart to expose hidden assumptions',
    normative: 'about how things ought to be',
    contingent: 'dependent on circumstances',
    situated: 'shaped by its particular context',
    embodied: 'experienced through the body',
    materiality: 'the physical-stuff-ness of a thing',
    agency: 'the capacity to act',
    subjectivity: 'the personal, first-person point of view',
    positionality: "the author's own standpoint and biases",
    nuanced: 'subtly complicated',
    unpack: 'analyze in careful detail',
    lens: 'a perspective you read a subject through',
    corpus: 'a body of texts under study',
    'peer-reviewed': 'vetted by other scholars before publishing',
    tenure: 'a permanent, hard-to-revoke academic post',
    abstract: 'the summary at the top of a paper',
    thesis: 'the central argument',
    dissertation: 'a book-length doctoral thesis',
    cohort: 'a group moving through a program together',
    salient: 'standing out as important',
    ostensibly: 'apparently — but perhaps not really',
    qua: 'in the capacity of; as',
    ergo: 'therefore',
    ipso: 'by that very fact ("ipso facto")',
    facto: 'in fact; in reality',
  },
  words: [
    'discourse',
    'hegemony',
    'dialectic',
    'epistemology',
    'ontology',
    'problematize',
    'interrogate',
    'liminal',
    'hermeneutic',
    'praxis',
    'heuristic',
    'paradigm',
    'framework',
    'methodology',
    'qualitative',
    'empirical',
    'theoretical',
    'intersectional',
    'postcolonial',
    'deconstruct',
    'normative',
    'contingent',
    'situated',
    'embodied',
    'materiality',
    'agency',
    'subjectivity',
    'positionality',
    'gesture',
    'troubling',
    'nuanced',
    'scaffolding',
    'foreground',
    'centering',
    'unpack',
    'complicate',
    'lens',
    'corpus',
    'literature',
    'citation',
    'footnote',
    'peer-reviewed',
    'tenure',
    'abstract',
    'thesis',
    'dissertation',
    'cohort',
    'seminar',
    'rigorous',
    'salient',
    'ostensibly',
    'qua',
    'ergo',
    'ipso',
    'facto',
    'vis-à-vis',
  ],
  openers: [
    'It could be argued that',
    'Drawing on Foucault,',
    'This paper interrogates',
    'As the literature suggests,',
    'Within this framework,',
    'One might problematize',
    'Ostensibly,',
  ],
  interjections: [
    '(see Figure 3).',
    'Further research is needed.',
    'This warrants unpacking.',
    'Citation needed.',
    'The data are inconclusive.',
    'But I digress.',
  ],
};
