import type { Theme } from './types.js';

/** The hedged, citation-laden prose of the seminar room. */
export const academia: Theme = {
  id: 'academia',
  name: 'Academia',
  description: 'It could be argued that this placeholder problematizes the discourse.',
  emoji: '🎓',
  accent: '#6e2b2b',
  defaultIntensity: 0.4,
  origin:
    'The hedged, citation-laden prose of the seminar room — where nothing simply ' +
    'is, it is "situated," "troubled," and "always already" something else ' +
    '(see Figure 3).',
  words: [
    'discourse',
    'hegemony',
    'dialectic',
    'epistemology',
    'ontology',
    'problematize',
    'interrogate',
    'liminal',
    'hermeneutic',
    'praxis',
    'heuristic',
    'paradigm',
    'framework',
    'methodology',
    'qualitative',
    'empirical',
    'theoretical',
    'intersectional',
    'postcolonial',
    'deconstruct',
    'normative',
    'contingent',
    'situated',
    'embodied',
    'materiality',
    'agency',
    'subjectivity',
    'positionality',
    'gesture',
    'troubling',
    'nuanced',
    'scaffolding',
    'foreground',
    'centering',
    'unpack',
    'complicate',
    'lens',
    'corpus',
    'literature',
    'citation',
    'footnote',
    'peer-reviewed',
    'tenure',
    'abstract',
    'thesis',
    'dissertation',
    'cohort',
    'seminar',
    'rigorous',
    'salient',
    'ostensibly',
    'qua',
    'ergo',
    'ipso',
    'facto',
    'vis-à-vis',
  ],
  openers: [
    'It could be argued that',
    'Drawing on Foucault,',
    'This paper interrogates',
    'As the literature suggests,',
    'Within this framework,',
    'One might problematize',
    'Ostensibly,',
  ],
  interjections: [
    '(see Figure 3).',
    'Further research is needed.',
    'This warrants unpacking.',
    'Citation needed.',
    'The data are inconclusive.',
    'But I digress.',
  ],
};
