import type { Theme } from './types.js';

/** The unmistakable clichés of AI-generated filler. Let's delve into this rich tapestry. */
export const aislop: Theme = {
  id: 'aislop',
  name: 'AI Slop',
  description: "Let's delve into this rich tapestry of placeholder text. I hope this helps!",
  emoji: '🤖',
  accent: '#0d9488',
  defaultIntensity: 0.8,
  glossary: {
    delve: 'AI for "look at"; the single most tell-tale word',
    tapestry: 'AI for "a mix of things," always "rich"',
    realm: 'AI for "area" or "field"',
    testament: 'AI for "proof" ("a testament to…")',
    beacon: 'AI for "example" ("a beacon of hope/innovation")',
    embark: 'AI for "start" ("embark on a journey")',
    navigate: 'AI for "deal with" ("navigate the landscape")',
    underscore: 'AI for "emphasize"',
    myriad: 'AI for "many"',
    plethora: 'AI for "lots"',
    furthermore: 'AI for "also," deployed relentlessly',
    multifaceted: 'AI for "complicated"',
    pivotal: 'AI for "important"',
    'ever-evolving': 'AI for "changing"',
    'game-changer': 'AI for "a good thing"',
  },
  words: [
    'delve',
    'tapestry',
    'realm',
    'testament',
    'beacon',
    'journey',
    'embark',
    'navigate',
    'landscape',
    'underscore',
    'leverage',
    'robust',
    'seamless',
    'elevate',
    'unlock',
    'harness',
    'foster',
    'pivotal',
    'crucial',
    'myriad',
    'plethora',
    'furthermore',
    'moreover',
    'intricate',
    'nuanced',
    'holistic',
    'vibrant',
    'bustling',
    'multifaceted',
    'comprehensive',
    'invaluable',
    'paramount',
    'treasure',
    'gem',
    'ever-evolving',
    'fast-paced',
    'game-changer',
    'cutting-edge',
    'dive',
    'conclusion',
  ],
  openers: [
    "In today's fast-paced world,",
    "It's important to note that",
    'In conclusion,',
    "Let's delve into",
    'At its core,',
    'Furthermore,',
    'When it comes to',
  ],
  interjections: [
    "But that's not all.",
    'The possibilities are endless.',
    "It's a testament to innovation.",
    "Let's unlock its full potential.",
    'In the ever-evolving landscape.',
    'Every journey begins with a single step.',
    'I hope this helps!',
  ],
};
