import type { Theme } from './types.js';

/** Edge-of-your-seat play-by-play. And the placeholder text goes ALL the way! */
export const announcer: Theme = {
  id: 'announcer',
  name: 'Sports Announcer',
  description: 'And the placeholder text goes ALL the way! Are you KIDDING me?!',
  emoji: '🎙️',
  accent: '#ea7317',
  defaultIntensity: 0.8,
  glossary: {
    downtown: 'from way out — a long-range shot',
    buzzer: 'the final horn ("buzzer-beater")',
    clutch: 'delivering under maximum pressure',
    dagger: 'the basket that puts the game away',
    hattrick: 'three goals by one player in a game',
    shutout: 'holding the opponent to zero',
    turnover: 'coughing up possession',
    dynasty: 'a team that wins, and keeps on winning',
    upset: 'when the underdog pulls it off',
    mvp: 'Most Valuable Player',
    goat: 'Greatest Of All Time',
    fundamentals: 'the unglamorous stuff that actually wins games',
    rebound: 'grabbing the missed shot',
    interception: 'stealing the ball out of the air',
  },
  words: [
    'downtown',
    'buzzer',
    'clutch',
    'momentum',
    'overtime',
    'comeback',
    'dagger',
    'highlight',
    'rookie',
    'veteran',
    'underdog',
    'dynasty',
    'hattrick',
    'shutout',
    'turnover',
    'fastbreak',
    'touchdown',
    'homerun',
    'grandslam',
    'knockout',
    'upset',
    'blowout',
    'halftime',
    'playoffs',
    'championship',
    'MVP',
    'GOAT',
    'fundamentals',
    'hustle',
    'rebound',
    'assist',
    'interception',
    'scoreboard',
    'replay',
    'sideline',
    'franchise',
  ],
  openers: [
    'Ladies and gentlemen,',
    "And here's the pitch —",
    'Oh, are you KIDDING me?!',
    'Folks, you will NOT believe this:',
    'Coming down to the wire,',
    'From the top of the key,',
    'He could go all the way —',
  ],
  interjections: [
    'GOAL!',
    'Are you not entertained?!',
    'Right at the buzzer!',
    'That is a DAGGER!',
    'What a play, folks!',
    'Send it to overtime!',
    'Get this man an MVP!',
  ],
};
