import type { Theme } from './types.js';

/** The earnest, evocative prose of the gallery wall-text. Very visceral. */
export const artist: Theme = {
  id: 'artist',
  name: 'Artist Statement',
  description: 'The work explores the liminal tension between filler and the void.',
  emoji: '🎨',
  accent: '#2440d8',
  defaultIntensity: 0.45,
  origin:
    'The earnest, evocative prose of the gallery wall-text — where the negative ' +
    'space is "doing a lot" and the medium dictates the message. Very visceral.',
  words: [
    'gesture',
    'negative',
    'space',
    'juxtaposition',
    'ephemeral',
    'visceral',
    'texture',
    'palette',
    'chiaroscuro',
    'impasto',
    'gestural',
    'mark-making',
    'picture',
    'plane',
    'composition',
    'tension',
    'movement',
    'rhythm',
    'form',
    'void',
    'materiality',
    'process',
    'intentional',
    'evocative',
    'raw',
    'authentic',
    'vulnerable',
    'exploration',
    'practice',
    'medium',
    'mixed',
    'abstraction',
    'figurative',
    'brutalist',
    'minimalist',
    'maximalist',
    'monochrome',
    'saturated',
    'muted',
    'ochre',
    'vermilion',
    'cobalt',
    'cadmium',
    'gesso',
    'varnish',
    'canvas',
    'plein',
    'air',
    'atelier',
    'oeuvre',
    'provocative',
    'transgressive',
    'liminal',
    'immersive',
    'site-specific',
    'installation',
    'interrogates',
    'dialogue',
  ],
  openers: [
    'The work explores',
    "I'm interested in the tension between",
    "It's really about",
    'Conceptually,',
    "There's a rawness to",
    'I let the medium dictate',
    "What I'm gesturing toward is",
  ],
  interjections: [
    'It speaks to me.',
    'Very visceral.',
    'The negative space is doing a lot.',
    "It's giving Basquiat.",
    'I need more cadmium.',
    'Process over product.',
  ],
};
