import type { Theme } from './types.js';

/** The tasting-note poetry of the specialty coffee bar. Oat milk, no foam. */
export const barista: Theme = {
  id: 'barista',
  name: 'Third-Wave Barista',
  description: 'A washed Ethiopian with notes of stone fruit and bright acidity.',
  emoji: '☕',
  accent: '#7a5230',
  defaultIntensity: 0.4,
  origin:
    'The tasting-note poetry of the specialty coffee bar — where the grind is ' +
    'dialed in, the crema is judged, and yes, that’s oat milk, no foam.',
  glossary: {
    espresso: 'a concentrated shot of pressure-brewed coffee',
    ristretto: 'a short, "restricted" espresso',
    lungo: 'a long, larger espresso',
    cortado: 'espresso cut with a little warm milk',
    cappuccino: 'espresso with steamed and foamed milk',
    macchiato: 'espresso "marked" with a dab of milk',
    americano: 'espresso let down with hot water',
    'pour-over': 'coffee brewed by pouring water through grounds',
    chemex: 'an hourglass-shaped pour-over brewer',
    aeropress: 'a plunger-style immersion brewer',
    gooseneck: 'a kettle with a precise, swan-necked spout',
    tamp: 'press the grounds down flat and firm',
    portafilter: 'the handled basket that holds the grounds',
    grind: 'how coarse or fine the coffee is ground',
    burr: 'the grinder that crushes beans evenly',
    dose: 'the weight of dry grounds used',
    yield: 'the weight of liquid coffee produced',
    extraction: 'drawing the flavor out of the grounds',
    channeling: 'water punching a fault through the puck — a flaw',
    crema: 'the golden foam crowning an espresso',
    microfoam: 'silky, finely steamed milk',
    rosetta: 'a leaf-shaped latte-art pattern',
    origin: "the coffee's source farm or region",
    yirgacheffe: 'a celebrated coffee region in Ethiopia',
    natural: 'beans dried inside the fruit (a process)',
    washed: 'beans pulped and washed clean (a process)',
    honey: 'beans dried with some fruit left on (a process)',
    acidity: 'the bright, tangy quality in the cup',
    body: 'how heavy or full the coffee feels',
    mouthfeel: 'the texture of the coffee in your mouth',
    third: 'the coffee-as-craft movement ("third wave")',
    roast: 'how dark the beans were cooked',
  },
  words: [
    'espresso',
    'ristretto',
    'lungo',
    'cortado',
    'cappuccino',
    'flat',
    'white',
    'macchiato',
    'americano',
    'pour-over',
    'chemex',
    'aeropress',
    'gooseneck',
    'kettle',
    'tamp',
    'portafilter',
    'grind',
    'burr',
    'dose',
    'yield',
    'extraction',
    'channeling',
    'crema',
    'microfoam',
    'latte',
    'art',
    'rosetta',
    'tulip',
    'single',
    'origin',
    'ethiopian',
    'yirgacheffe',
    'natural',
    'washed',
    'honey',
    'process',
    'tasting',
    'notes',
    'floral',
    'citrus',
    'stone',
    'fruit',
    'chocolate',
    'nutty',
    'bright',
    'acidity',
    'body',
    'mouthfeel',
    'third',
    'wave',
    'roast',
    'light',
    'medium',
    'oat',
    'milk',
    'beans',
    'freshly',
    'ground',
  ],
  openers: [
    'So this is a washed Ethiopian with',
    'Tasting notes of',
    "We're pulling this as a",
    'Honestly the extraction was',
    "I'm getting",
    'For the mouthfeel,',
    "It's a single-origin",
  ],
  interjections: [
    'Notes of stone fruit.',
    'Bright acidity.',
    'Oat milk, no foam.',
    "That's a nice crema.",
    'Dialing in the grind.',
    'Third wave, baby.',
  ],
};
