import type { Theme } from './types.js';

/** The tasting-note poetry of the specialty coffee bar. Oat milk, no foam. */
export const barista: Theme = {
  id: 'barista',
  name: 'Third-Wave Barista',
  description: 'A washed Ethiopian with notes of stone fruit and bright acidity.',
  emoji: '☕',
  accent: '#7a5230',
  defaultIntensity: 0.4,
  origin:
    'The tasting-note poetry of the specialty coffee bar — where the grind is ' +
    'dialed in, the crema is judged, and yes, that’s oat milk, no foam.',
  words: [
    'espresso',
    'ristretto',
    'lungo',
    'cortado',
    'cappuccino',
    'flat',
    'white',
    'macchiato',
    'americano',
    'pour-over',
    'chemex',
    'aeropress',
    'gooseneck',
    'kettle',
    'tamp',
    'portafilter',
    'grind',
    'burr',
    'dose',
    'yield',
    'extraction',
    'channeling',
    'crema',
    'microfoam',
    'latte',
    'art',
    'rosetta',
    'tulip',
    'single',
    'origin',
    'ethiopian',
    'yirgacheffe',
    'natural',
    'washed',
    'honey',
    'process',
    'tasting',
    'notes',
    'floral',
    'citrus',
    'stone',
    'fruit',
    'chocolate',
    'nutty',
    'bright',
    'acidity',
    'body',
    'mouthfeel',
    'third',
    'wave',
    'roast',
    'light',
    'medium',
    'oat',
    'milk',
    'beans',
    'freshly',
    'ground',
  ],
  openers: [
    'So this is a washed Ethiopian with',
    'Tasting notes of',
    "We're pulling this as a",
    'Honestly the extraction was',
    "I'm getting",
    'For the mouthfeel,',
    "It's a single-origin",
  ],
  interjections: [
    'Notes of stone fruit.',
    'Bright acidity.',
    'Oat milk, no foam.',
    "That's a nice crema.",
    'Dialing in the grind.',
    'Third wave, baby.',
  ],
};
