import type { Theme } from './types.js';

/** Hyperreal theory-speak: simulacra, the desert of the real, the precession of models. */
export const baudrillard: Theme = {
  id: 'baudrillard',
  name: 'Baudrillard',
  description: 'The placeholder precedes the text. Welcome to the desert of the real.',
  emoji: '🪞',
  accent: '#5b5f97',
  defaultIntensity: 0.7,
  glossary: {
    simulacra: 'copies for which no original ever existed',
    hyperreal: 'more real than real; the model standing in for reality',
    precession: 'the map now precedes the territory it once described',
    referent: 'the real thing a sign once pointed to, now missing',
    signifier: 'the form of a sign, drifting free of meaning',
    spectacle: 'reality replaced by, and consumed as, its image',
    implosion: 'meaning collapsing inward until distinctions vanish',
    seduction: 'the play of appearances that needs no truth beneath it',
    obscene: 'too visible, too present, stripped of all secrecy',
    desert: '"the desert of the real" — what remains after the map',
    code: 'the system that generates the signs we take for real',
    model: 'the template that reality now dutifully imitates',
    ecstasy: 'a quality pushed past its own extreme into pure form',
    virtual: 'real without ever having to be actual',
  },
  words: [
    'simulacra',
    'simulacrum',
    'simulation',
    'hyperreal',
    'hyperreality',
    'real',
    'desert',
    'referent',
    'sign',
    'signifier',
    'signified',
    'code',
    'model',
    'copy',
    'original',
    'representation',
    'image',
    'spectacle',
    'consumer',
    'object',
    'system',
    'seduction',
    'ecstasy',
    'obscene',
    'fatal',
    'precession',
    'map',
    'territory',
    'mirror',
    'void',
    'implosion',
    'abstraction',
    'symbolic',
    'virtual',
    'mediated',
    'nostalgia',
  ],
  openers: [
    'It could be argued that',
    'In the order of simulacra,',
    'The real, henceforth,',
    'We are, after all,',
    'Disneyland exists to conceal that',
    'There is no longer',
    'Henceforth,',
  ],
  interjections: [
    'The map precedes the territory.',
    'Welcome to the desert of the real.',
    'It is no longer a question of imitation.',
    'The simulacrum is true.',
    'There is no more referent.',
    'Nostalgia assumes its full meaning.',
    'The Gulf War did not take place.',
  ],
};
