import type { Theme } from './types.js';

/** The cadence of a forwarded email with seven layers of "Fwd:". */
export const boomer: Theme = {
  id: 'boomer',
  name: 'Boomer',
  description: 'Back in my day, placeholder text cost a nickel. Sent from my iPad.',
  emoji: '📠',
  accent: '#2f5b9c',
  defaultIntensity: 0.35,
  origin:
    'The cadence of a forwarded email with seven layers of "Fwd:" — well-meaning, ' +
    'slightly off-topic, ending in a blessing. Praying for you.',
  words: [
    'minivan',
    'casserole',
    'thermostat',
    'lawn',
    'sprinkler',
    'coupon',
    'manager',
    'warranty',
    'dial-up',
    'fax',
    'rotary',
    'phone',
    'retirement',
    'pension',
    'golf',
    'cul-de-sac',
    'recliner',
    'remote',
    'batteries',
    'newspaper',
    'crossword',
    'early-bird',
    'special',
    'buffet',
    'cruise',
    'grandkids',
    'facebook',
    'forwarded',
    'email',
    'chain',
    'letter',
    'doctor',
    'said',
    'back',
    'weather',
    'channel',
    'gas',
    'prices',
    'kids',
    'these',
    'days',
    'uphill',
    'both',
    'ways',
    'nickel',
    'bootstraps',
    'sears',
    'blockbuster',
    'lawnmower',
    'garage',
    'sale',
    'wallet',
    'checkbook',
    'matlock',
    'denture',
    'prune',
    'juice',
  ],
  openers: [
    'Back in my day,',
    'When I was your age,',
    'Nobody wants to work anymore, but',
    'I forwarded you an email about',
    'The doctor said',
    'In this economy,',
    "Kids these days don't know",
  ],
  interjections: [
    'Like and share!',
    'Sent from my iPad.',
    'Have you tried turning it off?',
    'Sincerely, Dad.',
    'Praying for you.',
    'Good morning!',
  ],
};
