import type { Theme } from './types.js';

/** Unhinged Italian-brainrot nonsense. Tralalero tralala, bombardiro crocodilo. */
export const brainrot: Theme = {
  id: 'brainrot',
  name: 'Italian Brainrot',
  description: 'Tralalero tralala — absolutely unhinged placeholder text. Bombardiro crocodilo.',
  emoji: '🤌',
  accent: '#16a34a',
  defaultIntensity: 0.85,
  glossary: {
    tralalero: 'a shark wearing blue Nike sneakers, allegedly',
    bombardiro: 'a crocodile-bomber aircraft hybrid, naturally',
    crocodilo: 'the back half of a bombardiro',
    sahur: 'said only after "tung tung tung," do not ask why',
    patapim: 'what inevitably follows "brr brr"',
    capuccino: 'a cappuccino that is also an assassin',
    assassino: 'see capuccino',
    chimpanzini: 'a chimpanzee fused with a banana, of course',
    bananini: 'the banana component of a chimpanzini',
    boneca: 'a doll fused with a frog',
    ambalabu: 'the frog component of a boneca',
    ballerina: 'a ballerina whose head is a cappuccino',
    glorbo: "nobody knows, and that is entirely the point",
    basta: 'enough! (an actual Italian word, for balance)',
    allora: '"so, then…" (also an actual Italian word)',
  },
  words: [
    'tralalero',
    'tralala',
    'bombardiro',
    'crocodilo',
    'tung',
    'sahur',
    'lirili',
    'larila',
    'bombombini',
    'gusini',
    'brr',
    'patapim',
    'capuccino',
    'assassino',
    'frigo',
    'camelo',
    'chimpanzini',
    'bananini',
    'trippi',
    'troppi',
    'trulimero',
    'trulicina',
    'boneca',
    'ambalabu',
    'spioniro',
    'golubiro',
    'ballerina',
    'cappuccina',
    'glorbo',
    'fruttodrillo',
    'mamma',
    'mia',
    'basta',
    'ecco',
    'allora',
    'prego',
  ],
  openers: [
    'Tralalero tralala,',
    'Brr brr patapim,',
    'Tung tung tung,',
    'Mamma mia,',
    'Allora, ecco —',
    'Bombardiro crocodilo:',
    'Lirilì larilà,',
  ],
  interjections: [
    'Tralalero tralala!',
    'Bombardiro crocodilo!',
    'Tung tung tung sahur!',
    'Capuccino assassino!',
    'Mamma mia, basta!',
    'Brr brr patapim!',
    'Chimpanzini bananini!',
  ],
};
