import type { Theme } from './types.js';

/** Filler text dictated by a cat at 3am. The audacity. */
export const cat: Theme = {
  id: 'cat',
  name: 'Cat',
  description: 'Filler text dictated by a cat at 3am. The audacity.',
  emoji: '🐈',
  accent: '#d96a2c',
  defaultIntensity: 0.55,
  origin:
    'As channelled from a small dictator who has decided the vase looks better ' +
    'on the floor. You are the staff.',
  words: [
    'meow',
    'purr',
    'knock',
    'glass',
    'off',
    'table',
    'treat',
    'nap',
    'sunbeam',
    'zoomies',
    'hairball',
    'box',
    'cardboard',
    'laser',
    'dot',
    'mouse',
    'feather',
    'scratch',
    'post',
    'litter',
    'hooman',
    'servant',
    'kibble',
    'tuna',
    'midnight',
    'chaos',
    'vase',
    'windowsill',
    'bird',
    'judging',
    'loaf',
    'biscuits',
    'kneading',
    'blep',
    'mlem',
    'toebeans',
    'whiskers',
    'tail',
    'floof',
    'chonk',
    'snack',
    'attack',
    'ignore',
    'affection',
    'demand',
    'sudden',
    'prance',
    'perch',
    'lap',
    'keyboard',
    'sit',
    'purrr',
    'forbidden',
    'counter',
    'curtain',
    'climb',
    'screaming',
    'empty',
    'bowl',
  ],
  openers: [
    'Hooman,',
    'Excuse me but',
    'I have decided that',
    'At precisely 3am,',
    'Against my better judgment,',
    'You will feed me because',
    'I knocked it over because',
  ],
  interjections: [
    'Meow.',
    'Feed me.',
    'Mlem.',
    'The audacity.',
    'I require attention now.',
    'Knocked it off the table.',
    'This is my box now.',
    'Screaming for no reason.',
  ],
};
