import type { Theme } from './types.js';

/** The original Latin-ish lorem ipsum vocabulary, for when you need the classic look. */
export const classic: Theme = {
  id: 'classic',
  name: 'Classic Lorem',
  description: 'The timeless Latin-flavored filler everyone knows.',
  emoji: '📜',
  accent: '#9a7b3f',
  defaultIntensity: 0,
  words: [
    'lorem',
    'ipsum',
    'dolor',
    'sit',
    'amet',
    'consectetur',
    'adipiscing',
    'elit',
    'sed',
    'do',
    'eiusmod',
    'tempor',
    'incididunt',
    'ut',
    'labore',
    'et',
    'dolore',
    'magna',
    'aliqua',
    'enim',
    'ad',
    'minim',
    'veniam',
    'quis',
    'nostrud',
    'exercitation',
    'ullamco',
    'laboris',
    'nisi',
    'aliquip',
    'ex',
    'ea',
    'commodo',
    'consequat',
    'duis',
    'aute',
    'irure',
    'in',
    'reprehenderit',
    'voluptate',
    'velit',
    'esse',
    'cillum',
    'fugiat',
    'nulla',
    'pariatur',
    'excepteur',
    'sint',
    'occaecat',
    'cupidatat',
    'non',
    'proident',
    'sunt',
    'culpa',
    'qui',
    'officia',
    'deserunt',
    'mollit',
    'anim',
    'id',
    'est',
    'laborum',
    'perspiciatis',
    'unde',
    'omnis',
    'iste',
    'natus',
    'error',
    'voluptatem',
    'accusantium',
    'doloremque',
    'laudantium',
    'totam',
    'rem',
    'aperiam',
    'eaque',
    'quae',
    'ab',
    'illo',
    'inventore',
    'veritatis',
  ],
};
