import type { Theme } from './types.js';

/** The breathless red-string-and-corkboard register. Follow the money. */
export const conspiracy: Theme = {
  id: 'conspiracy',
  name: 'Conspiracy',
  description: 'Wake up, sheeple. The placeholder text is connected. Do your research.',
  emoji: '🛸',
  accent: '#c0291f',
  defaultIntensity: 0.5,
  origin:
    'The breathless red-string-and-corkboard register where every coincidence is ' +
    'a clue and the truth is always [REDACTED]. Follow the money.',
  glossary: {
    sheeple: 'people who allegedly follow along without questioning',
    deep: 'a hidden, permanent power behind the government ("deep state")',
    state: 'the alleged shadow government',
    false: 'a staged event blamed on someone else ("false flag")',
    flag: 'the staged-attack ploy',
    chemtrails: 'the myth that aircraft contrails are secret chemicals',
    fluoride: 'a tap-water additive, and a favorite bogeyman',
    illuminati: 'a mythical secret order said to rule the world',
    psyop: 'a psychological operation meant to manipulate',
    narrative: 'the "official story" you are urged to distrust',
    redacted: 'blacked out; hidden from view',
    roswell: 'the 1947 New Mexico site of an alleged UFO crash',
    whistleblower: 'an insider who leaks the supposed truth',
    matrix: 'the idea that reality itself is a constructed illusion',
    simulation: 'the theory that we live inside a computer program',
  },
  words: [
    'wake',
    'up',
    'sheeple',
    'they',
    "don't",
    'want',
    'you',
    'to',
    'know',
    'follow',
    'the',
    'money',
    'deep',
    'state',
    'false',
    'flag',
    'chemtrails',
    'fluoride',
    'frequencies',
    'lizard',
    'people',
    'illuminati',
    'new',
    'world',
    'order',
    'simulation',
    'glitch',
    'matrix',
    'controlled',
    'opposition',
    'psyop',
    'agenda',
    'narrative',
    'mainstream',
    'media',
    'bought',
    'paid',
    'research',
    'connect',
    'dots',
    'red',
    'pill',
    'rabbit',
    'hole',
    'classified',
    'redacted',
    'area',
    'roswell',
    'birds',
    "aren't",
    'real',
    'flat',
    'earth',
    'vibrations',
    'third',
    'eye',
    'awakening',
    'cover-up',
    'whistleblower',
  ],
  openers: [
    'Wake up, sheeple —',
    "They don't want you to know,",
    'Connect the dots:',
    'Do your own research, but',
    'Coincidence? I think not —',
    'Follow the money and',
    "What the media won't tell you:",
  ],
  interjections: [
    'Coincidence? I think not.',
    'Wake up.',
    "It's all connected.",
    'Do your research.',
    "They're watching.",
    'Follow the money.',
    '[REDACTED]',
  ],
};
