import type { Theme } from './types.js';

/** Buzzword-dense business speak for mockups of dashboards, decks, and landing pages. */
export const corporate: Theme = {
  id: 'corporate',
  name: 'Corporate Synergy',
  description: 'Leverage best-in-class buzzwords to circle back on placeholder copy.',
  emoji: '📈',
  words: [
    'synergy',
    'leverage',
    'scalable',
    'bandwidth',
    'stakeholder',
    'paradigm',
    'streamline',
    'optimize',
    'actionable',
    'deliverable',
    'roadmap',
    'pivot',
    'disrupt',
    'ecosystem',
    'holistic',
    'agile',
    'ideate',
    'iterate',
    'pipeline',
    'alignment',
    'value',
    'proposition',
    'core',
    'competency',
    'low-hanging',
    'fruit',
    'circle',
    'back',
    'deep',
    'dive',
    'touch',
    'base',
    'move',
    'needle',
    'mission-critical',
    'best-in-class',
    'cross-functional',
    'data-driven',
    'growth',
    'hacking',
    'frictionless',
    'seamless',
    'robust',
    'enterprise',
    'cloud-native',
    'turnkey',
    'thought',
    'leadership',
    'north',
    'star',
    'metric',
    'velocity',
    'runway',
    'onboarding',
    'KPI',
    'ROI',
    'quarter',
    'vertical',
    'horizontal',
    'integration',
    'innovation',
    'transformation',
  ],
  openers: [
    'Going forward,',
    'At the end of the day,',
    'To be transparent,',
    'Per my last email,',
    "Let's circle back —",
    'Moving the needle,',
    'From a high level,',
  ],
  interjections: [
    "Let's take this offline.",
    'We should sync on that.',
    'Big if true.',
    'Adding it to the roadmap.',
    'Win-win.',
    "Let's double-click on this.",
  ],
};
