import type { Theme } from './types.js';

/** Buzzword-dense business speak for mockups of dashboards, decks, and landing pages. */
export const corporate: Theme = {
  id: 'corporate',
  name: 'Corporate Synergy',
  description: 'Leverage best-in-class buzzwords to circle back on placeholder copy.',
  emoji: '📈',
  accent: '#2563eb',
  glossary: {
    synergy: 'combined output, allegedly greater than the sum of its parts',
    leverage: 'to use — as a verb, for absolutely everything',
    scalable: 'will not fall over if it gets popular',
    bandwidth: 'spare time or attention',
    stakeholder: 'anyone with an opinion on it',
    paradigm: 'a way of doing things',
    streamline: 'remove steps (and sometimes people)',
    optimize: 'make marginally better',
    actionable: 'something you could actually act on',
    deliverable: 'a thing you owe someone',
    roadmap: 'a plan that will change',
    pivot: 'change direction; quietly admit the last plan failed',
    disrupt: 'upend an industry, or claim to',
    ecosystem: 'a market, dressed up as biology',
    holistic: 'considering the whole thing',
    agile: 'a way of working — often invoked, rarely followed',
    ideate: 'to have ideas (corporate verb)',
    iterate: 'try again, slightly differently',
    pipeline: 'deals or work in progress',
    alignment: 'agreement, eventually',
    proposition: 'the pitch ("value proposition")',
    competency: 'a skill ("core competency")',
    'low-hanging': 'the easy wins ("low-hanging fruit")',
    fruit: 'the easy win',
    needle: 'the metric you hope to "move"',
    'mission-critical': 'important enough to say twice',
    'best-in-class': 'better than rivals, according to us',
    'cross-functional': 'involving several teams at once',
    'data-driven': 'justified with numbers',
    frictionless: 'easy to use',
    seamless: 'with no visible joins',
    robust: 'unlikely to break',
    enterprise: 'big, slow, and expensive',
    'cloud-native': 'built to run in the cloud',
    turnkey: 'ready to use out of the box',
    kpi: 'Key Performance Indicator — a number you watch',
    roi: 'Return On Investment — was it worth it',
    velocity: 'how fast the team ships',
    runway: 'how many months of cash remain',
    onboarding: 'getting someone started',
    vertical: 'an industry segment',
    integration: 'making two systems talk to each other',
    innovation: 'newness, asserted',
    transformation: 'big change, with a capital T',
  },
  words: [
    'synergy',
    'leverage',
    'scalable',
    'bandwidth',
    'stakeholder',
    'paradigm',
    'streamline',
    'optimize',
    'actionable',
    'deliverable',
    'roadmap',
    'pivot',
    'disrupt',
    'ecosystem',
    'holistic',
    'agile',
    'ideate',
    'iterate',
    'pipeline',
    'alignment',
    'value',
    'proposition',
    'core',
    'competency',
    'low-hanging',
    'fruit',
    'circle',
    'back',
    'deep',
    'dive',
    'touch',
    'base',
    'move',
    'needle',
    'mission-critical',
    'best-in-class',
    'cross-functional',
    'data-driven',
    'growth',
    'hacking',
    'frictionless',
    'seamless',
    'robust',
    'enterprise',
    'cloud-native',
    'turnkey',
    'thought',
    'leadership',
    'north',
    'star',
    'metric',
    'velocity',
    'runway',
    'onboarding',
    'KPI',
    'ROI',
    'quarter',
    'vertical',
    'horizontal',
    'integration',
    'innovation',
    'transformation',
  ],
  openers: [
    'Going forward,',
    'At the end of the day,',
    'To be transparent,',
    'Per my last email,',
    "Let's circle back —",
    'Moving the needle,',
    'From a high level,',
  ],
  interjections: [
    "Let's take this offline.",
    'We should sync on that.',
    'Big if true.',
    'Adding it to the roadmap.',
    'Win-win.',
    "Let's double-click on this.",
  ],
};
