import type { Theme } from './types.js';

/** The flat, blunt, gezellig charm of the Lowlands. Doei! */
export const dutch: Theme = {
  id: 'dutch',
  name: 'Dutch',
  description: 'Doe maar gewoon, dan doe je al gek genoeg. Lekker placeholder, hoor.',
  emoji: '🧀',
  accent: '#f0670a',
  defaultIntensity: 0.55,
  origin:
    'The flat, blunt, gezellig charm of the Lowlands — bicycles, cheese, and a ' +
    'Tikkie for that one coffee you bought them. Doei!',
  words: [
    'gezellig',
    'lekker',
    'fiets',
    'stroopwafel',
    'kaas',
    'gouda',
    'edam',
    'hagelslag',
    'bitterballen',
    'borrel',
    'mosselen',
    'oranje',
    'koning',
    'dijk',
    'polder',
    'windmolen',
    'tulpen',
    'klompen',
    'grachten',
    'regen',
    'fietspad',
    'drop',
    'frikandel',
    'kroket',
    'patat',
    'mayonaise',
    'bruin',
    'café',
    'terras',
    'pils',
    'jenever',
    'doei',
    'hoi',
    'dankjewel',
    'alsjeblieft',
    'weertje',
    'niet',
    'normaal',
    'doe',
    'maar',
    'gewoon',
    'dan',
    'ben',
    'je',
    'al',
    'gek',
    'genoeg',
    'tikkie',
    'sturen',
    'even',
    'kijken',
    'hoor',
    'joh',
    'zeg',
    'nou',
    'fietsen',
    'kopje',
    'koffie',
  ],
  openers: [
    'Doe maar gewoon,',
    'Lekker bezig,',
    'Even Apeldoorn bellen —',
    'Niet normaal,',
    'Gezellig,',
    'Ik stuur je een tikkie voor',
    'Drie keer is',
  ],
  interjections: [
    'Lekker!',
    'Gezellig.',
    'Doei!',
    'Niet normaal.',
    'Ik stuur een tikkie.',
    'Één koekje bij de koffie.',
    'Joh!',
  ],
};
