import type { Theme } from './types.js';

/** The hyper-compressed, irony-poisoned dialect of the group chat. */
export const genz: Theme = {
  id: 'genz',
  name: 'Gen Z',
  description: 'ngl this placeholder text is lowkey bussin, no cap fr fr.',
  emoji: '😭',
  accent: '#0bb5a6',
  defaultIntensity: 0.65,
  origin:
    'The hyper-compressed, irony-poisoned dialect of the group chat. It’s giving ' +
    'placeholder. Bestie, the rizz is immaculate.',
  words: [
    'rizz',
    'gyatt',
    'fr',
    'ngl',
    'lowkey',
    'highkey',
    'slay',
    'bussin',
    'sus',
    'cap',
    'bet',
    'fam',
    'vibe',
    'vibes',
    'mid',
    'based',
    'cringe',
    'simp',
    'stan',
    'ratio',
    'mood',
    'slaps',
    'bops',
    'fire',
    'lit',
    'deadass',
    'periodt',
    'bestie',
    'girlie',
    'bro',
    'gng',
    'ong',
    'iykyk',
    'sheesh',
    'valid',
    'ick',
    'era',
    'main',
    'character',
    'delulu',
    'npc',
    'aura',
    'points',
    'cooked',
    'glazing',
    'yapping',
    'mewing',
    'situationship',
    'beige',
    'flag',
    'green',
    'red',
    'unc',
    'cooking',
    'locked',
    'goated',
    'pookie',
    'menace',
  ],
  openers: [
    'ngl',
    'lowkey',
    'no cap',
    'deadass',
    'bestie',
    'the way that',
    'not me',
    "it's giving",
  ],
  interjections: [
    'fr fr.',
    'sheesh.',
    'no cap.',
    "it's giving.",
    'ratio.',
    'we love to see it.',
    "and that's on periodt.",
    'lowkey cooked.',
  ],
};
