import type { Theme } from './types.js';

/** Cyber-thriller technobabble for terminals, dashboards, and "we're in" moments. */
export const hacker: Theme = {
  id: 'hacker',
  name: 'Hacker Terminal',
  description: 'Cyber-thriller technobabble. We need to bypass the mainframe.',
  emoji: '👾',
  accent: '#16a34a',
  glossary: {
    mainframe: 'a big central computer',
    firewall: 'a network gatekeeper',
    protocol: 'the agreed rules for how machines talk',
    encryption: 'scrambling data so only a key can unlock it',
    payload: 'the part of an attack that does the work',
    exploit: 'code that abuses a flaw',
    kernel: "the operating system's core",
    daemon: 'a program running quietly in the background',
    packet: 'a small unit of network data',
    subnet: 'a slice of a larger network',
    proxy: 'a go-between server',
    cipher: 'an encryption scheme',
    rootkit: 'stealthy malware buried deep in the system',
    backdoor: 'a hidden way in',
    override: 'force past a control',
    bypass: 'go around a safeguard',
    breach: 'a successful break-in',
    node: 'a single device on a network',
    binary: 'ones and zeros',
    hexadecimal: 'base-16 numbers',
    algorithm: 'a step-by-step procedure',
    buffer: 'a temporary data store',
    overflow: 'writing past a buffer — a classic bug',
    injection: 'sneaking commands in through input',
    handshake: 'the ritual that opens a connection',
    token: 'a credential string',
    hash: 'a fixed-length fingerprint of data',
    salt: 'random data mixed in before hashing',
    entropy: 'randomness',
    gateway: 'a network entry and exit point',
    sandbox: 'an isolated space to run untrusted code',
    honeypot: 'a decoy set up to lure attackers',
    'zero-day': 'an unknown, unpatched flaw',
    malware: 'malicious software',
    trojan: 'malware disguised as something harmless',
    botnet: 'a swarm of hijacked machines',
    ice: 'Intrusion Countermeasures — cyberpunk for security',
    darknet: 'the hidden, unindexed corners of the net',
    compiler: 'turns source code into a runnable program',
    stack: 'memory used for function calls',
    heap: 'memory used for dynamic data',
    pointer: 'an address of data in memory',
    thread: 'a single line of execution',
    socket: 'one endpoint of a network connection',
    vector: 'a path of attack',
  },
  words: [
    'mainframe',
    'firewall',
    'protocol',
    'encryption',
    'payload',
    'exploit',
    'kernel',
    'daemon',
    'packet',
    'subnet',
    'proxy',
    'cipher',
    'rootkit',
    'backdoor',
    'override',
    'bypass',
    'breach',
    'node',
    'cluster',
    'binary',
    'hexadecimal',
    'algorithm',
    'recursive',
    'buffer',
    'overflow',
    'injection',
    'handshake',
    'token',
    'hash',
    'salt',
    'entropy',
    'bandwidth',
    'latency',
    'gateway',
    'cluster',
    'sandbox',
    'honeypot',
    'zero-day',
    'malware',
    'trojan',
    'botnet',
    'ICE',
    'mesh',
    'darknet',
    'uplink',
    'terminal',
    'compiler',
    'stack',
    'heap',
    'pointer',
    'thread',
    'socket',
    'tunnel',
    'vector',
    'matrix',
    'grid',
    'core',
    'access',
    'granted',
    'denied',
  ],
  openers: [
    "I'm in.",
    'Rerouting through',
    'Compiling',
    'Initiating',
    'Bypassing the',
    'Decrypting',
    'Tracing the',
  ],
  interjections: [
    'Access granted.',
    'We need more time!',
    'Enhance.',
    "They're tracing us.",
    'Connection established.',
    'Firewall down.',
  ],
};
