import type { Theme } from './types.js';

/** Cyber-thriller technobabble for terminals, dashboards, and "we're in" moments. */
export const hacker: Theme = {
  id: 'hacker',
  name: 'Hacker Terminal',
  description: 'Cyber-thriller technobabble. We need to bypass the mainframe.',
  emoji: '👾',
  words: [
    'mainframe',
    'firewall',
    'protocol',
    'encryption',
    'payload',
    'exploit',
    'kernel',
    'daemon',
    'packet',
    'subnet',
    'proxy',
    'cipher',
    'rootkit',
    'backdoor',
    'override',
    'bypass',
    'breach',
    'node',
    'cluster',
    'binary',
    'hexadecimal',
    'algorithm',
    'recursive',
    'buffer',
    'overflow',
    'injection',
    'handshake',
    'token',
    'hash',
    'salt',
    'entropy',
    'bandwidth',
    'latency',
    'gateway',
    'cluster',
    'sandbox',
    'honeypot',
    'zero-day',
    'malware',
    'trojan',
    'botnet',
    'ICE',
    'mesh',
    'darknet',
    'uplink',
    'terminal',
    'compiler',
    'stack',
    'heap',
    'pointer',
    'thread',
    'socket',
    'tunnel',
    'vector',
    'matrix',
    'grid',
    'core',
    'access',
    'granted',
    'denied',
  ],
  openers: [
    "I'm in.",
    'Rerouting through',
    'Compiling',
    'Initiating',
    'Bypassing the',
    'Decrypting',
    'Tracing the',
  ],
  interjections: [
    'Access granted.',
    'We need more time!',
    'Enhance.',
    "They're tracing us.",
    'Connection established.',
    'Firewall down.',
  ],
};
