import type { Theme } from './types.js';

/** The passive-aggressive officialese of the Homeowners Association. */
export const hoa: Theme = {
  id: 'hoa',
  name: 'HOA Notice',
  description: 'This is your second courtesy notice regarding the placeholder mailbox.',
  emoji: '🏡',
  accent: '#5b7a4f',
  defaultIntensity: 0.4,
  origin:
    'The passive-aggressive officialese of the Homeowners Association — where your ' +
    'mailbox is the wrong beige and the garden gnome is, regrettably, in ' +
    'violation. Per the bylaws.',
  glossary: {
    bylaws: "the association's internal rules",
    covenant: 'a binding rule that runs with your property',
    violation: 'breaking a rule',
    compliance: 'following the rules',
    regulation: 'an official rule',
    palette: 'the list of approved colors ("color palette")',
    ordinance: 'a local law',
    easement: "another party's right to cross your land",
    setback: 'required distance from the property line',
    assessment: 'a fee charged to owners',
    dues: 'mandatory membership fees',
    quorum: 'the minimum members needed to vote',
    seconded: 'a motion supported by a second member',
    restriction: 'a limit on what you may do',
    permit: 'official permission to do something',
  },
  words: [
    'bylaws',
    'covenant',
    'violation',
    'notice',
    'compliance',
    'mailbox',
    'regulation',
    'approved',
    'color',
    'palette',
    'fence',
    'height',
    'ordinance',
    'easement',
    'setback',
    'lawn',
    'ornament',
    'garden',
    'gnome',
    'prohibited',
    'trash',
    'bin',
    'visible',
    'curb',
    'driveway',
    'parking',
    'guest',
    'permit',
    'board',
    'meeting',
    'minutes',
    'quorum',
    'motion',
    'seconded',
    'assessment',
    'dues',
    'fine',
    'warning',
    'second',
    'courtesy',
    'reminder',
    'holiday',
    'decorations',
    'removed',
    'basketball',
    'hoop',
    'shed',
    'pressure',
    'wash',
    'mulch',
    'hedge',
    'trimmed',
    'flag',
    'pole',
    'restriction',
    'satellite',
    'dish',
    'regrettably',
  ],
  openers: [
    'Per the bylaws,',
    'This is your second courtesy notice regarding',
    'The board has determined that',
    'In accordance with Section 7.2,',
    'It has come to our attention that',
    'Kindly be advised that',
    'As a friendly reminder,',
  ],
  interjections: [
    'See attached notice.',
    'A fine has been assessed.',
    'This is your final warning.',
    'Please remit dues promptly.',
    'The board thanks you.',
    'Compliance is appreciated.',
  ],
};
