import type { Theme } from './types.js';

/** Canadian rink-rat slang for beauties, dangles, and gongshows. Sauce it top cheese, bud. */
export const hockey: Theme = {
  id: 'hockey',
  name: 'Hockey Bro',
  description: 'Filler from a beauty in the room — wheel, snipe, celly. Ferda, bud.',
  emoji: '🏒',
  accent: '#0e7ea8',
  defaultIntensity: 0.8,
  glossary: {
    beauty: 'a great guy; the highest hockey compliment',
    bud: 'friend; deployed roughly every five words',
    sauce: 'a crisp, accurate pass right on the tape',
    dangle: 'a slick stickhandling move',
    chirp: 'to trash-talk an opponent',
    gongshow: 'total, glorious chaos',
    barn: 'the arena',
    twig: 'a hockey stick',
    biscuit: 'the puck',
    mitts: 'the hands; stickhandling skill',
    celly: 'a goal celebration',
    bender: 'a bad skater (ankles bending inward)',
    duster: 'a benchwarmer who collects dust',
    grocery: 'a player who basically just carries the snacks',
    plug: 'a useless player',
    tendy: 'the goaltender',
    lettuce: 'great hair',
    gino: 'a goal',
    chiclets: 'teeth (the ones you still have)',
    hoser: 'a loser, said with great affection',
    ferda: '"for the boys" — the team, the cause, everything',
  },
  words: [
    'beauty',
    'beauties',
    'bud',
    'buddy',
    'sauce',
    'saucy',
    'dangle',
    'dangles',
    'chirp',
    'chirpin',
    'gongshow',
    'barn',
    'twig',
    'biscuit',
    'mitts',
    'wheelin',
    'snipe',
    'snipin',
    'celly',
    'bender',
    'duster',
    'grocery',
    'plug',
    'tendy',
    'lettuce',
    'flow',
    'gino',
    'chiclets',
    'hoser',
    'ferda',
    'rink',
    'puck',
    'zamboni',
    'apples',
    'tarp',
  ],
  openers: [
    'Beauty, listen —',
    'No word of a lie, bud,',
    'Honestly, ferda,',
    'Geez, what a gongshow,',
    'Top cheese, baby —',
    'Send it, boys,',
    "Givin' 'er,",
  ],
  interjections: [
    'What a beauty!',
    'Top cheddar!',
    'Sauce city!',
    'Wheel, snipe, celly!',
    "He's a gamer, bud.",
    "Chirpin' already, eh?",
    "Givin' 'er ferda!",
  ],
};
