import type { Theme } from './types.js';

/** Reality-TV reunion energy: receipts, prosecco, and "my truth." */
export const housewives: Theme = {
  id: 'housewives',
  name: 'Real Housewives',
  description: "I'm not here to make friends — but make it iconic. I have the receipts.",
  emoji: '🍷',
  accent: '#db2777',
  defaultIntensity: 0.8,
  glossary: {
    receipts: "the proof you've been screenshotting for this exact moment",
    prosecco: 'a beverage; also a projectile',
    namaste: 'said in the half-second before going for the throat',
    truth: '"my truth" — my version of events, non-negotiable',
    unbothered: 'visibly, profoundly bothered',
    gaslighting: 'what everyone at the table accuses everyone else of',
    audacity: 'the nerve, the gall, the sheer cheek of it',
    delusional: "how you describe a friend's account of the same night",
    shade: 'an insult with excellent manners',
    betrayal: 'a minor scheduling conflict, dramatized',
    reunion: 'the televised trial where it all finally comes out',
    manifesting: 'wanting something, loudly, as a personality',
    boundaries: 'firmly announced, never once observed',
    toxic: 'anyone currently disagreeing with you',
    era: 'a phase you are branding ("my healing era")',
  },
  words: [
    'drama',
    'messy',
    'blessed',
    'iconic',
    'receipts',
    'prosecco',
    'namaste',
    'journey',
    'truth',
    'energy',
    'blocked',
    'unbothered',
    'gaslighting',
    'audacity',
    'delusional',
    'fabulous',
    'glam',
    'shade',
    'betrayal',
    'alliance',
    'reunion',
    'brunch',
    'wine',
    'manifesting',
    'healing',
    'boundaries',
    'toxic',
    'projecting',
    'accountability',
    'narrative',
    'villain',
    'era',
    'friendship',
  ],
  openers: [
    "I'm not here to make friends, but",
    'With all due respect,',
    'Let me be clear:',
    'Say what you want about me,',
    'In this house,',
    'Honestly? My truth is,',
    'I said what I said —',
  ],
  interjections: [
    'I have the receipts.',
    "She's delusional.",
    "It's giving betrayal.",
    'Namaste, then.',
    "We're not friends anymore.",
    'This is my truth.',
    'Blocked. Unfollowed.',
  ],
};
