import type { Theme } from './types.js';

/**
 * Huttese — the language of Jabba and the denizens of Tatooine's cantinas.
 * Bo shuda! A galaxy-far-far-away flavor of filler text.
 */
export const huttese: Theme = {
  id: 'huttese',
  name: 'Huttese Cantina',
  description: 'Bargon yanah coto da eunhost. Filler from a galaxy far, far away.',
  emoji: '🐸',
  // Hidden Easter egg: not shown in listings. Summon it with the seed "jabba".
  hidden: true,
  defaultIntensity: 0.55,
  origin:
    'Huttese is the fictional trade language of the Star Wars galaxy, spoken ' +
    'by Jabba the Hutt and heard across Tatooine. Its sound was devised by ' +
    'sound designer Ben Burtt, loosely inspired by Quechua. "Bo shuda" is a ' +
    'greeting, "Boska" means "let\'s go", and "poodoo" is... best left ' +
    'untranslated at the dinner table.',
  words: [
    'bargon',
    'bota',
    'chuba',
    'coona',
    'doompa',
    'goodde',
    'jee',
    'jee-jee',
    'killee',
    'mooie',
    'peedunkey',
    'poodoo',
    'wanta',
    'yatuka',
    'achuta',
    'bantha',
    'boonowa',
    'tweepi',
    'coo',
    'dopa',
    'gardo',
    'hagwa',
    'jeedai',
    'keepuna',
    'kung',
    'moocha',
    'nee',
    'choo',
    'noah',
    'stoopa',
    'wermo',
    'whiforce',
    'yaté',
    'tagwa',
    'murishani',
    'nudd',
    'chaa',
    'eniki',
    'okkota',
    'pateesa',
    'rundee',
    'sleemo',
    'tonta',
    'uba',
    'wooky',
    'crispo',
    'grancha',
    'haku',
    'inkabunga',
    'jujuminmee',
    'loca',
    'mwahaha',
    'naga',
    'opa',
    'punsmuggle',
    'rana',
    'see',
    'tee-tocky',
    'vota',
    'yocola',
  ],
  openers: [
    'Achuta,',
    'H’chu apenkee,',
    'Koona t’chuta —',
    'Jabba wanna',
    'Bo shuda,',
    'Ee youdsa,',
    'Mee jewz ku,',
  ],
  interjections: [
    'Boska!',
    'Chuba!',
    'Ho ho ho!',
    'Bo shuda.',
    'De wanna wanga.',
    'Stoopa!',
    'Bargon u noa-a-uyat.',
  ],
};
