import type { Theme } from './types.js';

/** Wordless-manual register: insert dowel A into panel B. Do not overtighten. */
export const ikea: Theme = {
  id: 'ikea',
  name: 'IKEA Instructions',
  description: 'Some assembly required. Insert dowel A into placeholder B. Do not overtighten.',
  emoji: '🪑',
  accent: '#0058a3',
  defaultIntensity: 0.75,
  glossary: {
    dowel: "a small wooden peg you will be exactly one short of",
    allen: 'the little L-shaped key (allen wrench), included, singular',
    hex: 'the shape of every bolt head in the bag',
    flatpack: 'a wardrobe convincingly disguised as a coffee table',
    sawdust: 'the wardrobe, compressed and renamed',
    billy: 'the bookcase everyone has owned',
    kallax: 'the cube shelf everyone has owned',
    malm: 'the bed frame everyone has owned',
    poang: 'the bouncy armchair everyone has owned',
    blahaj: 'the shark; the genuine reason you came',
    flarb: 'a part with no discernible purpose',
    snorb: 'where the flarb attaches, probably',
    gronk: 'do not, under any circumstances, overtighten the gronk',
    fig: 'as in "see fig. 4," which is blank',
  },
  words: [
    'assemble',
    'insert',
    'align',
    'fasten',
    'tighten',
    'rotate',
    'attach',
    'secure',
    'dowel',
    'panel',
    'bracket',
    'hinge',
    'screw',
    'bolt',
    'washer',
    'peg',
    'plank',
    'shelf',
    'allen',
    'hex',
    'diagram',
    'step',
    'part',
    'fig',
    'optional',
    'included',
    'required',
    'flatpack',
    'sawdust',
    'billy',
    'kallax',
    'malm',
    'poang',
    'flarb',
    'snorb',
    'blahaj',
    'gronk',
    'fjord',
    'plonk',
    'skadis',
  ],
  openers: [
    'Step 1:',
    'Before you begin,',
    'Note: do not',
    'Insert part A into',
    'See fig. 4 —',
    'Tighten gently;',
    'Allen key included.',
  ],
  interjections: [
    'Do not overtighten.',
    'Some assembly required.',
    'Two people recommended.',
    'Part missing? Visit store.',
    '(diagram intentionally blank)',
    'Now repeat six times.',
    'It wobbles. Acceptable.',
  ],
};
