import type { Theme } from './types.js';

/** The dense, hedge-everything register of contracts and statutes. */
export const legalese: Theme = {
  id: 'legalese',
  name: 'Legalese',
  description: 'Whereas the party of the first part hereby furnishes filler text.',
  emoji: '⚖️',
  accent: '#8a2433',
  defaultIntensity: 0.45,
  origin:
    'The dense, hedge-everything register of contracts and statutes — doublets ' +
    '("terms and conditions"), Latin maxims, and a deep fear of ambiguity. ' +
    'Notwithstanding the foregoing.',
  glossary: {
    heretofore: 'until now',
    whereas: 'given that — the opener of a contract recital',
    party: 'a person bound by the contract',
    parties: 'the people bound by the contract',
    aforementioned: 'already mentioned above',
    hereinafter: 'from here on, referred to as…',
    indemnify: 'promise to cover their losses',
    indemnification: 'the promise to cover losses',
    liability: 'legal responsibility for harm',
    pursuant: 'in accordance with',
    notwithstanding: 'despite',
    covenant: 'a binding promise',
    herein: 'in this document',
    thereof: 'of that',
    therein: 'in that',
    hereby: 'by this very act',
    stipulate: 'agree to as a condition',
    jurisdiction: "a court's authority to decide",
    plaintiff: 'the one bringing the suit',
    defendant: 'the one being sued',
    counsel: 'a lawyer',
    breach: 'breaking the agreement',
    tort: 'a civil wrong (not a crime)',
    statute: 'a written law',
    provision: 'a single term or condition',
    clause: 'a single term of a contract',
    subsection: 'a numbered sub-part',
    addendum: 'an added section',
    exhibit: 'an attached supporting document',
    warranty: 'a guarantee',
    disclaimer: 'a denial of responsibility',
    damages: 'money owed for harm done',
    remedy: 'the legal fix for a wrong',
    waiver: 'giving up a right',
    severability: 'if one part is void, the rest survives',
    governing: 'which law controls ("governing law")',
    binding: 'legally enforceable',
    consideration: 'what each side gives in exchange',
    force: 'an unforeseeable event excusing performance ("force majeure")',
    majeure: 'superior force; an act of God',
    arbitration: 'private dispute resolution outside court',
    venue: 'the place a case is heard',
    fiduciary: 'bound to act in your interest',
    escrow: 'held by a neutral third party until terms are met',
    lien: 'a claim on property as security for a debt',
    encumbrance: 'a claim or burden attached to property',
    estoppel: "a bar against contradicting one's earlier word",
    res: 'the thing itself',
    ipsa: 'itself',
    loquitur: 'speaks — "the thing speaks for itself"',
    prima: 'first; on its face',
    facie: 'face — "prima facie" means at first sight',
    bona: 'good',
    fide: 'faith — "bona fide" means in good faith',
    habeas: 'you shall have (the body) — an order to produce a detainee',
    subpoena: 'an order to appear or hand over evidence',
  },
  words: [
    'heretofore',
    'whereas',
    'party',
    'parties',
    'aforementioned',
    'hereinafter',
    'indemnify',
    'indemnification',
    'liability',
    'pursuant',
    'notwithstanding',
    'covenant',
    'herein',
    'thereof',
    'therein',
    'hereby',
    'stipulate',
    'jurisdiction',
    'plaintiff',
    'defendant',
    'counsel',
    'breach',
    'tort',
    'statute',
    'provision',
    'clause',
    'subsection',
    'addendum',
    'exhibit',
    'warranty',
    'disclaimer',
    'arising',
    'damages',
    'remedy',
    'waiver',
    'severability',
    'governing',
    'binding',
    'executed',
    'undersigned',
    'consideration',
    'obligations',
    'representations',
    'warranties',
    'force',
    'majeure',
    'arbitration',
    'venue',
    'counterparty',
    'fiduciary',
    'escrow',
    'lien',
    'encumbrance',
    'estoppel',
    'res',
    'ipsa',
    'loquitur',
    'prima',
    'facie',
    'bona',
    'fide',
    'habeas',
    'subpoena',
  ],
  openers: [
    'Whereas,',
    'Notwithstanding the foregoing,',
    'Pursuant to Section 4(a),',
    'For the avoidance of doubt,',
    'In consideration of the mutual covenants,',
    'Subject to the terms herein,',
    'The party of the first part hereby',
  ],
  interjections: [
    'See Exhibit A.',
    'Time is of the essence.',
    'All rights reserved.',
    'This clause shall survive termination.',
    'Without prejudice.',
    'Per the addendum.',
  ],
};
