import type { Theme } from './types.js';

/** The dense, hedge-everything register of contracts and statutes. */
export const legalese: Theme = {
  id: 'legalese',
  name: 'Legalese',
  description: 'Whereas the party of the first part hereby furnishes filler text.',
  emoji: '⚖️',
  accent: '#8a2433',
  defaultIntensity: 0.45,
  origin:
    'The dense, hedge-everything register of contracts and statutes — doublets ' +
    '("terms and conditions"), Latin maxims, and a deep fear of ambiguity. ' +
    'Notwithstanding the foregoing.',
  words: [
    'heretofore',
    'whereas',
    'party',
    'parties',
    'aforementioned',
    'hereinafter',
    'indemnify',
    'indemnification',
    'liability',
    'pursuant',
    'notwithstanding',
    'covenant',
    'herein',
    'thereof',
    'therein',
    'hereby',
    'stipulate',
    'jurisdiction',
    'plaintiff',
    'defendant',
    'counsel',
    'breach',
    'tort',
    'statute',
    'provision',
    'clause',
    'subsection',
    'addendum',
    'exhibit',
    'warranty',
    'disclaimer',
    'arising',
    'damages',
    'remedy',
    'waiver',
    'severability',
    'governing',
    'binding',
    'executed',
    'undersigned',
    'consideration',
    'obligations',
    'representations',
    'warranties',
    'force',
    'majeure',
    'arbitration',
    'venue',
    'counterparty',
    'fiduciary',
    'escrow',
    'lien',
    'encumbrance',
    'estoppel',
    'res',
    'ipsa',
    'loquitur',
    'prima',
    'facie',
    'bona',
    'fide',
    'habeas',
    'subpoena',
  ],
  openers: [
    'Whereas,',
    'Notwithstanding the foregoing,',
    'Pursuant to Section 4(a),',
    'For the avoidance of doubt,',
    'In consideration of the mutual covenants,',
    'Subject to the terms herein,',
    'The party of the first part hereby',
  ],
  interjections: [
    'See Exhibit A.',
    'Time is of the essence.',
    'All rights reserved.',
    'This clause shall survive termination.',
    'Without prejudice.',
    'Per the addendum.',
  ],
};
