import type { Theme } from './types.js';

/** Mewing, mogging, and canthal tilt. Placeholder text, but it ascended. */
export const looksmaxxer: Theme = {
  id: 'looksmaxxer',
  name: 'Looksmaxxer',
  description: 'Placeholder text, mogged. Mew, fix your canthal tilt, and ascend.',
  emoji: '🗿',
  accent: '#7c3aed',
  defaultIntensity: 0.8,
  glossary: {
    mewing: 'pressing your tongue to the roof of your mouth for a sharper jaw',
    mogging: 'out-looking someone so hard they feel it across the room',
    mog: 'to dominate someone in appearance',
    looksmaxx: 'to maximize your looks by any means available',
    jawline: 'the holy grail; everything is downstream of it',
    canthal: 'of the corners of the eye ("canthal tilt")',
    tilt: 'the upward angle of the eyes (positive = good)',
    hunter: 'deep-set, hooded, vaguely predatory ("hunter eyes")',
    gigachad: 'the theoretical peak of male aesthetics',
    sigma: 'a lone-wolf alpha who plays by his own rules',
    ascend: 'to finally cross into being attractive',
    gymmaxx: 'to looksmaxx via the gym',
    glowup: 'a dramatic improvement in appearance over time',
    aura: 'intangible presence points, gained and lost in real time',
    mogger: 'one who mogs',
    maxilla: 'the upper jaw bone; forward growth is the dream',
  },
  words: [
    'mewing',
    'mogging',
    'mog',
    'mogged',
    'mogs',
    'looksmaxx',
    'looksmaxxing',
    'jawline',
    'canthal',
    'tilt',
    'hunter',
    'eyes',
    'gigachad',
    'chad',
    'sigma',
    'ascend',
    'ascended',
    'gymmaxx',
    'glowup',
    'glow',
    'mewer',
    'mogger',
    'aura',
    'frame',
    'maxilla',
    'ramus',
    'philtrum',
    'gonial',
    'zygos',
    'debloat',
    'collagen',
    'hardmaxx',
    'softmaxx',
    'ascension',
  ],
  openers: [
    'Bro, just mew,',
    'Lowkey mogging everyone,',
    'Canthal tilt looking insane,',
    'Time to ascend,',
    'Gigachad behavior:',
    'Real sigma move —',
    'Looksmaxx-pilled,',
  ],
  interjections: [
    'He mogged the whole room.',
    'Mew harder.',
    'Aura plus one thousand.',
    "It's so over. (We're so back.)",
    'Bones are everything.',
    'Glow-up loading.',
    'Sigma grindset.',
  ],
};
