import type { Theme } from './types.js';

/** Salty seafaring filler. Arr. */
export const pirate: Theme = {
  id: 'pirate',
  name: 'Pirate Shanty',
  description: 'Salty seafaring filler for landlubbers who need dummy text. Arr.',
  emoji: '🏴‍☠️',
  accent: '#0f7a82',
  words: [
    'ahoy',
    'matey',
    'booty',
    'plunder',
    'doubloon',
    'scallywag',
    'landlubber',
    'cannon',
    'cutlass',
    'galleon',
    'kraken',
    'parley',
    'scurvy',
    'bilge',
    'rat',
    'grog',
    'rum',
    'treasure',
    'chest',
    'compass',
    'horizon',
    'tide',
    'anchor',
    'mast',
    'sail',
    'crow',
    'nest',
    'plank',
    'mutiny',
    'captain',
    'first',
    'mate',
    'quartermaster',
    'cove',
    'reef',
    'maelstrom',
    'leviathan',
    'jolly',
    'roger',
    'hearties',
    'savvy',
    'yardarm',
    'starboard',
    'port',
    'bow',
    'stern',
    'keel',
    'rigging',
    'spyglass',
    'cutpurse',
    'buccaneer',
    'corsair',
    'marooned',
    'shanty',
    'fathom',
    'briny',
    'deep',
    'gold',
  ],
  openers: [
    'Arr,',
    'Avast ye,',
    'Shiver me timbers,',
    'By the powers,',
    'Yo ho ho,',
    'Blimey,',
    'Batten down the hatches,',
  ],
  interjections: [
    'Arr!',
    'Yo ho ho!',
    'Dead men tell no tales.',
    'To the depths!',
    'Yer a pirate now, savvy?',
    'Hoist the colors!',
  ],
};
