import type { Theme } from './types.js';

/** Kitchen-nightmare rage (with the occasional, devastating bit of praise). Affectionate parody. */
export const ramsay: Theme = {
  id: 'ramsay',
  name: 'Gordon Ramsay',
  description: "Placeholder text so raw it's still mooing. It's an IDIOT SANDWICH.",
  emoji: '👨‍🍳',
  accent: '#c1121f',
  defaultIntensity: 0.85,
  glossary: {
    raw: 'not cooked; pronounced with maximum disgust',
    bland: 'criminally under-seasoned; a cardinal sin',
    donkey: 'an idiot, screamed with a strange affection',
    muppet: 'a fool, specifically a fool in a kitchen',
    wellington: 'the beef dish he will ask for, every single time',
    seasoning: 'the thing you forgot, you donkey',
    risotto: 'gluey, apparently, no matter what you do',
    scallops: 'rubbery, apparently, no matter what you do',
    finesse: 'the quality your plate is missing',
    michelin: "the star you are absolutely not getting like this",
    brigade: 'the kitchen crew',
    mise: '"mise en place" — your prep, which is a disgrace',
    refire: 'cook it again, properly this time',
    exquisite: 'rare, genuine, and slightly alarming praise',
    panini: 'as in "you absolute panini"',
  },
  words: [
    'raw',
    'bland',
    'dry',
    'frozen',
    'overcooked',
    'undercooked',
    'soggy',
    'disgusting',
    'disaster',
    'nightmare',
    'donkey',
    'muppet',
    'panini',
    'seasoning',
    'risotto',
    'scallops',
    'wellington',
    'sauce',
    'plating',
    'garnish',
    'finesse',
    'beautiful',
    'gorgeous',
    'stunning',
    'exquisite',
    'michelin',
    'brigade',
    'service',
    'station',
    'refire',
    'mise',
    'redo',
    'bin',
    'lamb',
    'pan',
    'heat',
  ],
  openers: [
    'Right, listen to me:',
    'Oh my god,',
    'Where is the —',
    'Taste it. TASTE IT:',
    'You donkey,',
    'Finally, some good —',
    'Come here, come here:',
  ],
  interjections: [
    "It's RAW!",
    "Where's the lamb sauce?!",
    'You absolute muppet.',
    "It's an idiot sandwich.",
    'Beautiful. Stunning.',
    'Get out. GET OUT.',
    'This is a disaster.',
  ],
};
