import type { Theme } from './types.js';

/** Feverish symbolist vision: a season in hell, the drunken boat, the alchemy of the word. */
export const rimbaud: Theme = {
  id: 'rimbaud',
  name: 'Rimbaud',
  description: 'I is another. A long, reasoned derangement of all the placeholder senses.',
  emoji: '⛵',
  accent: '#9a3412',
  defaultIntensity: 0.75,
  glossary: {
    vowels: 'each has a color, per his sonnet "Voyelles"',
    voyant: 'the "seer" — the poet must make himself one',
    derangement: '"a long, immense, reasoned derangement of all the senses"',
    illumination: 'a prose-poem vision (from "Illuminations")',
    absinthe: 'the green muse of the poètes maudits',
    alchemy: '"the alchemy of the word" — turning language to gold',
    abyss: 'the void he keeps leaning over to look into',
    drunken: 'as in "Le Bateau ivre," the drunken boat',
    eternity: '"It has been found again. What? Eternity."',
    azure: 'the impossible, oppressive blue overhead',
    delirium: 'a section of "A Season in Hell"',
    maelstrom: 'the whirlpool the drunken boat rides out',
    phosphor: 'the glowing chemical light of his visions',
    aurora: 'transcendent dawn-light',
  },
  words: [
    'vowels',
    'vowel',
    'azure',
    'abyss',
    'angel',
    'vision',
    'derangement',
    'senses',
    'season',
    'hell',
    'illumination',
    'drunken',
    'boat',
    'dawn',
    'ember',
    'absinthe',
    'comet',
    'phosphor',
    'marsh',
    'lichen',
    'aurora',
    'splendor',
    'vertigo',
    'eternity',
    'sea',
    'sun',
    'ardor',
    'delirium',
    'sorcery',
    'alchemy',
    'ash',
    'ivory',
    'emerald',
    'scarlet',
    'silence',
    'infinite',
    'voyant',
    'maelstrom',
    'frost',
  ],
  openers: [
    'I is another —',
    'One evening,',
    'It has been found again:',
    'I dreamed of',
    'O seasons, o châteaux,',
    'By the azure,',
    'Idle youth,',
  ],
  interjections: [
    'I is another.',
    'Eternity, found again.',
    'A long derangement of the senses.',
    'O seasons, o châteaux!',
    'The drunken boat drifts on.',
    'I alone hold the key.',
    'Down with the azure!',
  ],
};
