import type { Theme } from './types.js';

/** Silicon Valley pitch-deck energy. We're basically Uber, but for ipsum. */
export const startup: Theme = {
  id: 'startup',
  name: 'Startup Pitch',
  description: "We're disrupting placeholder text. It's like Uber, but for words.",
  emoji: '🚀',
  accent: '#6d4aff',
  glossary: {
    disrupt: 'upend an established industry',
    unicorn: 'a startup valued at $1 billion or more',
    runway: 'how many months of cash remain',
    burn: 'cash spent per month ("burn rate")',
    pivot: 'change the plan',
    traction: 'evidence that people actually want it',
    'product-market': 'when the product truly fits the market ("fit")',
    fit: 'the match between product and demand',
    moonshot: 'a wildly ambitious bet',
    ship: 'release it',
    mvp: 'Minimum Viable Product — the smallest useful version',
    'pre-seed': 'the earliest sliver of funding',
    'series-a': 'the first big venture round',
    valuation: 'what investors say the company is worth',
    cap: 'the ownership ledger ("cap table")',
    vesting: 'earning your equity over time',
    equity: 'ownership shares',
    founder: 'the person who started it',
    angel: 'an early individual investor',
    venture: 'venture capital — risky money for fast growth',
    hypergrowth: 'scaling extremely fast',
    flywheel: 'a self-reinforcing growth loop',
    churn: 'customers who leave',
    retention: 'customers who stay',
    viral: 'spreading from user to user',
    'first-mover': 'first to stake out a market',
    blitzscale: 'grow recklessly fast to win the market',
    bootstrap: 'self-fund, with no investors',
    lean: 'a build-measure-learn, minimal-waste method',
    stealth: 'operating in secret ("stealth mode")',
    beta: 'a pre-release test version',
    waitlist: 'people queued up for access',
    okr: 'Objectives & Key Results — a goal-setting system',
    'category-defining': 'so new it invents its own category',
  },
  words: [
    'disrupt',
    'unicorn',
    'runway',
    'burn',
    'rate',
    'pivot',
    'traction',
    'product-market',
    'fit',
    'moonshot',
    'hustle',
    'grind',
    'ship',
    'iterate',
    'MVP',
    'pre-seed',
    'series-a',
    'valuation',
    'cap',
    'table',
    'vesting',
    'equity',
    'founder',
    'pitch',
    'deck',
    'angel',
    'investor',
    'venture',
    'scale',
    'hypergrowth',
    'flywheel',
    'network',
    'effect',
    'platform',
    'frictionless',
    'onboarding',
    'churn',
    'retention',
    'engagement',
    'viral',
    'loop',
    'growth',
    'first-mover',
    'blitzscale',
    'ramen',
    'profitable',
    'bootstrap',
    'lean',
    'stealth',
    'mode',
    'launch',
    'beta',
    'waitlist',
    'roadmap',
    'north-star',
    'OKR',
    'synergy',
    'ecosystem',
    'category-defining',
  ],
  openers: [
    "We're basically",
    "It's like Uber but for",
    'Imagine a world where',
    'Our north star is',
    'At scale,',
    "We're not just a company, we're",
    'The TAM for',
  ],
  interjections: [
    "We're pre-revenue but post-vision.",
    'Think bigger.',
    "It's a category-defining play.",
    "We'll figure out monetization later.",
    'Move fast.',
    "It's a marathon and a sprint.",
  ],
};
