import type { Theme } from './types.js';

/** Silicon Valley pitch-deck energy. We're basically Uber, but for ipsum. */
export const startup: Theme = {
  id: 'startup',
  name: 'Startup Pitch',
  description: "We're disrupting placeholder text. It's like Uber, but for words.",
  emoji: '🚀',
  accent: '#6d4aff',
  words: [
    'disrupt',
    'unicorn',
    'runway',
    'burn',
    'rate',
    'pivot',
    'traction',
    'product-market',
    'fit',
    'moonshot',
    'hustle',
    'grind',
    'ship',
    'iterate',
    'MVP',
    'pre-seed',
    'series-a',
    'valuation',
    'cap',
    'table',
    'vesting',
    'equity',
    'founder',
    'pitch',
    'deck',
    'angel',
    'investor',
    'venture',
    'scale',
    'hypergrowth',
    'flywheel',
    'network',
    'effect',
    'platform',
    'frictionless',
    'onboarding',
    'churn',
    'retention',
    'engagement',
    'viral',
    'loop',
    'growth',
    'first-mover',
    'blitzscale',
    'ramen',
    'profitable',
    'bootstrap',
    'lean',
    'stealth',
    'mode',
    'launch',
    'beta',
    'waitlist',
    'roadmap',
    'north-star',
    'OKR',
    'synergy',
    'ecosystem',
    'category-defining',
  ],
  openers: [
    "We're basically",
    "It's like Uber but for",
    'Imagine a world where',
    'Our north star is',
    'At scale,',
    "We're not just a company, we're",
    'The TAM for',
  ],
  interjections: [
    "We're pre-revenue but post-vision.",
    'Think bigger.',
    "It's a category-defining play.",
    "We'll figure out monetization later.",
    'Move fast.',
    "It's a marathon and a sprint.",
  ],
};
