import type { Theme } from './types.js';

/** Calm, mindful, lowercase-energy filler for wellness and meditation mockups. */
export const zen: Theme = {
  id: 'zen',
  name: 'Zen Garden',
  description: 'Calm, mindful filler. Breathe in placeholder, breathe out copy.',
  emoji: '🍃',
  accent: '#4f8f6e',
  words: [
    'breathe',
    'stillness',
    'presence',
    'flow',
    'balance',
    'harmony',
    'serene',
    'gentle',
    'mindful',
    'awareness',
    'intention',
    'grounded',
    'centered',
    'release',
    'surrender',
    'softly',
    'whisper',
    'ripple',
    'water',
    'stone',
    'mountain',
    'horizon',
    'dawn',
    'dusk',
    'blossom',
    'petal',
    'leaf',
    'bamboo',
    'lantern',
    'incense',
    'tea',
    'ceremony',
    'meadow',
    'meadowlark',
    'tide',
    'moon',
    'lotus',
    'koi',
    'ripples',
    'silence',
    'space',
    'light',
    'shadow',
    'warmth',
    'glow',
    'embrace',
    'nurture',
    'bloom',
    'root',
    'branch',
    'sky',
    'cloud',
    'mist',
    'dew',
    'morning',
    'evening',
    'quiet',
    'gratitude',
    'peace',
  ],
  openers: [
    'Gently,',
    'In this moment,',
    'With each breath,',
    'Softly now,',
    'As the morning settles,',
    'Returning to the breath,',
  ],
  interjections: [
    'Be here now.',
    'Let it go.',
    'Inhale. Exhale.',
    'All is well.',
    'This too shall pass.',
  ],
};
